#ifndef TEST_HARDWARE_TEST_CONFIG_H
#define TEST_HARDWARE_TEST_CONFIG_H

#define HARDWARE_TEST_NONE  0
#define HARDWARE_TEST_MOTOR 7

#ifndef HARDWARE_TEST_MODE
#define HARDWARE_TEST_MODE HARDWARE_TEST_MOTOR
#endif

#endif
